name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    verify-tomls:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Checkout another public repo
              uses: actions/checkout@v4
              with:
                  repository: pgdogdev/pgdog
                  ref: main
                  path: pgdog-source
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Install CMake 3.31
              run: |
                  sudo apt update && sudo apt install mold -y
                  sudo apt remove cmake
                  sudo pip3 install cmake==3.31.6
                  cmake --version
            - name: Build
              run: cargo build
              working-directory: pgdog-source
            - name: Install test dependencies
              run: sudo pip3 install -r tests/requirements.txt
            - name: Run tests
              run: python3 tests/test_code_blocks.py pgdog-source/target/debug/pgdog
