name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  verify-tomls:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: ci/bun

      - name: Collect snippets
        run: bun run "ci/bun/scripts/collectSnippets.ts"
        working-directory: ci/bun

      - name: Verify snippets
        run: bash ci/bash/verify_snippets.bash

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verification-log
          path: verification-log.json
