name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  verify-tomls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
        working-directory: ci/bun
      - name: Run all tests
        run: bun run "ci/bun/scripts/verifyTomls.ts"
      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verification-log
          path: verification-log.json
